### ISSUE TITLE
some questions about the work flow

### ISSUE THREAD

**Issue by dreaminglwj** [raymond1860/idr#12]
I got 0x05 only from Radio terminal when I sent "find card" command to sam from uart.
Just send 0x05 to the idcard2?

**Comment by raymond1860** [comment]
Please read SAM document for more details. Normally idr will send "\xAA\xAA\xAA\x96\x69\x00\x03\x20\x01\x22" when finding card command was executed. It will be okay if ID2 card existed. The response data should be "\xAA\xAA\xAA\x96\x69\xXX\xXX\xXX..." . The "XX" is the value returned from SAM. So 0x05 only return ,it must be something wrong.
